[workspace]
members = [
    "contracts/auction",
    "contracts/lockdrop",
    "contracts/credits",
    "contracts/vesting-lp",
    "contracts/vesting-managed",
    "contracts/astroport/*"
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
